FROM ocelotuproar/alpine-node:7.2.1
CMD [ "npm", "start" ]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install
ONBUILD COPY . /usr/src/app
